CREATE SEQUENCE seq_cod_material
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_cod_venta
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_rut_cliente
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO DMJSJSNT_MATERIALES (COD_MATERIAL, NOMBRE_MATERIAL, CANTIDAD_DISPONIBLE, PRECIO, COD_BODEGA)
VALUES (seq_cod_material.NEXTVAL, 'Material ', , , );

INSERT INTO DMJSJSNT_VENTAS (COD_VENTA, COD_USUARIO, COD_MATERIAL, RUT_CLIENTE, FECHA_VENTA, TOTAL_VENTA)
VALUES (seq_cod_venta.NEXTVAL, , , , SYSDATE,);

INSERT INTO DMJSJSNT_CLIENTES (RUT_CLIENTE, NOMBRE_CLIENTE, APELLIDO1_CLIENTE, APELLIDO2_CLIENTE, CORREO_CLIENTE)
VALUES (seq_rut_cliente.NEXTVAL, '', '', '', '');
